# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Prefecture.create(name: "北海道", code: "01", region_name: "北海道,東北", area: "")
Prefecture.create(name: "青森", code: "02", region_name: "北海道,東北", area: "")
Prefecture.create(name: "岩手", code: "03", region_name: "北海道,東北", area: "")
Prefecture.create(name: "宮城", code: "04", region_name: "北海道,東北", area: "")
Prefecture.create(name: "秋田", code: "05", region_name: "北海道,東北", area: "")
Prefecture.create(name: "山形", code: "06", region_name: "北海道,東北", area: "")
Prefecture.create(name: "福島", code: "07", region_name: "北海道,東北", area: "")
Prefecture.create(name: "茨城", code: "08", region_name: "関東", area: "")
Prefecture.create(name: "栃木", code: "09", region_name: "関東", area: "")
Prefecture.create(name: "群馬", code: "10", region_name: "関東", area: "")
Prefecture.create(name: "埼玉", code: "11", region_name: "関東", area: "")
Prefecture.create(name: "千葉", code: "12", region_name: "関東", area: "")
Prefecture.create(name: "東京", code: "13", region_name: "関東", area: "")
Prefecture.create(name: "神奈川", code: "14", region_name: "関東", area: "")
Prefecture.create(name: "新潟", code: "15", region_name: "北陸,甲信越", area: "")
Prefecture.create(name: "富山", code: "16", region_name: "北陸,甲信越", area: "")
Prefecture.create(name: "石川", code: "17", region_name: "北陸,甲信越", area: "")
Prefecture.create(name: "福井", code: "18", region_name: "北陸,甲信越", area: "")
Prefecture.create(name: "山梨", code: "19", region_name: "北陸,甲信越", area: "")
Prefecture.create(name: "長野", code: "20", region_name: "北陸,甲信越", area: "")
Prefecture.create(name: "岐阜", code: "21", region_name: "東海,関西", area: "")
Prefecture.create(name: "静岡", code: "22", region_name: "東海,関西", area: "")
Prefecture.create(name: "愛知", code: "23", region_name: "東海,関西", area: "")
Prefecture.create(name: "三重", code: "24", region_name: "東海,関西", area: "")
Prefecture.create(name: "滋賀", code: "25", region_name: "東海,関西", area: "")
Prefecture.create(name: "京都", code: "26", region_name: "東海,関西", area: "")
Prefecture.create(name: "大阪", code: "27", region_name: "東海,関西", area: "")
Prefecture.create(name: "兵庫", code: "28", region_name: "東海,関西", area: "")
Prefecture.create(name: "奈良", code: "29", region_name: "東海,関西", area: "")
Prefecture.create(name: "和歌山", code: "30", region_name: "東海,関西", area: "")
Prefecture.create(name: "鳥取", code: "31", region_name: "中国,四国", area: "")
Prefecture.create(name: "島根", code: "32", region_name: "中国,四国", area: "")
Prefecture.create(name: "岡山", code: "33", region_name: "中国,四国", area: "")
Prefecture.create(name: "広島", code: "34", region_name: "中国,四国", area: "")
Prefecture.create(name: "山口", code: "35", region_name: "中国,四国", area: "")
Prefecture.create(name: "徳島", code: "36", region_name: "中国,四国", area: "")
Prefecture.create(name: "香川", code: "37", region_name: "中国,四国", area: "")
Prefecture.create(name: "愛媛", code: "38", region_name: "中国,四国", area: "")
Prefecture.create(name: "高知", code: "39", region_name: "中国,四国", area: "")
Prefecture.create(name: "福岡", code: "40", region_name: "九州,沖縄", area: "")
Prefecture.create(name: "佐賀", code: "41", region_name: "九州,沖縄", area: "")
Prefecture.create(name: "長崎", code: "42", region_name: "九州,沖縄", area: "")
Prefecture.create(name: "熊本", code: "43", region_name: "九州,沖縄", area: "")
Prefecture.create(name: "大分", code: "44", region_name: "九州,沖縄", area: "")
Prefecture.create(name: "宮崎", code: "45", region_name: "九州,沖縄", area: "")
Prefecture.create(name: "鹿児島", code: "46", region_name: "九州,沖縄", area: "")
Prefecture.create(name: "沖縄", code: "47", region_name: "九州,沖縄", area: "")